version: "3.7"

services:
  api:
    container_name: spring-graphql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
